baseURL = 'https://rasinstitute.github.io/vic_project_website/'
languageCode = 'en-uk'
title = 'Virtual Innovation Consortium'
theme = 'ananke'
favicon = 'favicon.ico'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  site_logo = "images/vic_logo.png"
  custom_css = ["custom.css"]   # Optional, just for documentation
  custom_head = ["head-custom.html"]
  testmessage = 'Tttt'
  description= 'dasddss'

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

[[menu.main]]
  name = "Consortium"
  url = "/consortium/"
  weight = 2


